'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {validate}=require('./broker-catalog.cjs'),{capture}=require('./oanda-instruments.cjs');
const template=require('../docs/release-review/BROKER-CATALOG-TEMPLATE.json');
function fixture(){const c=structuredClone(template);Object.assign(c,{version:'TEST-ONLY',broker:'SYNTHETIC',platform:'TEST',server:'TEST',account_type:'TEST',account_currency:'USD',effective_from:'2026-01-01T00:00:00Z',effective_until:'2026-02-01T00:00:00Z',sources:[{id:'test',issuer:'TEST ONLY',reference:'synthetic',sha256:'a'.repeat(64),retrieved_at:'2026-01-01T00:00:00Z'}]});const s=c.symbols[0];Object.assign(s,{symbol:'TEST_A',base_currency:'EUR',quote_currency:'USD',contract_size:'100000',price_digits:5,tick_size:'0.00001',pip_size:'0.0001',minimum_lot:'0.01',maximum_lot:'10',lot_step:'0.01',source_ids:['test']});for(const v of Object.values(s))if(v&&typeof v==='object'&&!Array.isArray(v))Object.assign(v,{description:'SYNTHETIC TEST ONLY',source_ids:['test']});return c;}
test('blank intake fails and structurally complete data never claims verified broker authority',()=>{assert.equal(validate(template).valid,false);const r=validate(fixture());assert.equal(r.valid,true);assert.equal(r.broker_authority_verified,false);});
test('rejects duplicate symbols, missing cost sources, invalid lot range and effective dates',()=>{for(const change of [c=>c.symbols.push(c.symbols[0]),c=>c.symbols[0].swaps.source_ids=['missing'],c=>c.symbols[0].maximum_lot='0.001',c=>c.effective_until='2025-01-01T00:00:00Z',c=>c.effective_from='2026-02-30T00:00:00Z']){const c=fixture();change(c);assert.equal(validate(c).valid,false);}});
test('version hash changes when a broker cost schedule changes',()=>{const c=fixture(),before=validate(c).content_sha256;c.symbols[0].commission.description='Changed synthetic fee';assert.notEqual(validate(c).content_sha256,before);});
test('practice intake only sends GET to fixed broker host and preserves raw instrument evidence',async()=>{const raw=JSON.stringify({instruments:[{name:'EUR_USD',type:'CURRENCY',minimumTradeSize:'1'}]});const r=await capture({token:'test-secret',accountId:'101-001-123-001',fetchImpl:async(url,opts)=>{assert.equal(url,'https://api-fxpractice.oanda.com/v3/accounts/101-001-123-001/instruments');assert.equal(opts.method,'GET');assert.equal(opts.redirect,'error');return {ok:true,text:async()=>raw};}});assert.equal(r.raw_response,raw);assert.equal(r.production_verified,false);assert.equal(JSON.stringify(r).includes('test-secret'),false);assert.equal(JSON.stringify(r).includes('101-001-123-001'),false);});
test('missing credentials, HTTP errors and duplicate instruments cannot produce a snapshot',async()=>{await assert.rejects(capture({}),/Configure/);await assert.rejects(capture({token:'test',accountId:'101-001-123-001',fetchImpl:async()=>({ok:false,status:401})}),/HTTP 401/);await assert.rejects(capture({token:'test',accountId:'101-001-123-001',fetchImpl:async()=>({ok:true,text:async()=>JSON.stringify({instruments:[{name:'X'},{name:'X'}]})})}),/duplicate/);});
