'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {PRODUCT,PRICES}=require('./consumer-live-policy.cjs');
const {PLANS}=require('./consumer-core.cjs');
function harness(options={}){
 const data=new Map(),calls=[];let serial=0;
 const snapshot=path=>({exists:data.has(path),data:()=>data.get(path)});
 function ref(path){return {path,get:async()=>snapshot(path),set:async(v,o)=>data.set(path,o?.merge?{...data.get(path),...v}:v),collection:name=>collection(path+'/'+name)};}
 function collection(path){return {doc:id=>ref(path+'/'+(id||'auto'+(++serial))),orderBy(){return this;},limit(){return this;},get:async()=>({docs:[...data].filter(([k])=>k.startsWith(path+'/')&&!k.slice(path.length+1).includes('/')).map(([k,v])=>({id:k.split('/').pop(),data:()=>v})),size:0})};}
 const db={collection,runTransaction:async fn=>fn({get:async r=>snapshot(r.path),set:(r,v,o)=>r.set(v,o),create:(r,v)=>r.set(v),delete:r=>data.delete(r.path)})};
 function sub(tier='starter'){return {id:'sub_paid',customer:'cus_owner',livemode:true,status:'active',metadata:{product:PRODUCT,fynx_uid:'owner',tier},items:{data:[{quantity:1,price:{id:PRICES[tier],livemode:true,type:'recurring',unit_amount:PLANS[tier].cents,currency:'usd',recurring:{interval:'month',interval_count:1,usage_type:'licensed'}}}]},latest_invoice:{customer:'cus_owner',livemode:true,status:'paid',paid:true}};}
 const state={subscriptions:options.paid?[sub(options.tier)]:[],sessions:[],failCreate:false};
 const stripe={subscriptions:{list:async()=>{if(options.stripeDown)throw Error('Stripe unavailable');return {data:state.subscriptions};}},prices:{retrieve:async id=>{const tier=Object.keys(PRICES).find(t=>PRICES[t]===id);return {...sub(tier).items.data[0].price,active:true,...options.price};}},customers:{create:async(...args)=>{calls.push(['customer',...args]);return {id:'cus_owner'};}},checkout:{sessions:{list:async()=>({data:state.sessions}),retrieve:async()=>({status:'expired'}),expire:async id=>calls.push(['expire',id]),create:async(...args)=>{calls.push(['checkout',...args]);if(state.failCreate)throw Error('Timeout');return {id:'cs_new',url:'https://checkout.stripe.com/c/pay/cs_new'};}}},billingPortal:{configurations:{create:async()=>({id:'bpc_owner'})},sessions:{create:async args=>{calls.push(['portal',args]);return {url:'https://billing.stripe.com/session/live'};}}}};
 class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
 const module={exports:{}};const stubs={'firebase-functions/v1':{https:{HttpsError},runWith:()=>({https:{onCall:f=>f}})},'firebase-admin':{firestore:()=>db,auth:()=>({getUser:async()=>({email:'owner@example.invalid',disabled:false,...options.user})})},stripe:function(){return stripe;}};
 vm.runInNewContext(fs.readFileSync(__dirname+'/consumer-live-workspace.cjs','utf8'),{module,exports:module.exports,process:{env:{FYNX_CONSUMER_STRIPE_SECRET_KEY:options.key||'sk_live_UNIT_TEST_ONLY'}},require:n=>stubs[n]||require(n),Date});
 if(options.customer||options.paid)data.set('fynxConsumerLive/owner',{customer:'cus_owner'});
 return {call:(d,uid='owner')=>module.exports._test.handler(d,uid?{auth:{uid}}:{}),data,calls,state,sub};
}
test('requires authentication and enabled account',async()=>{await assert.rejects(harness().call({action:'status'},null),{code:'unauthenticated'});await assert.rejects(harness({user:{disabled:true}}).call({action:'status'}),{code:'permission-denied'});});
test('rejects sandbox keys and unknown actions',async()=>{await assert.rejects(harness({key:'sk_test_SAMPLE'}).call({action:'status'}),{code:'failed-precondition'});await assert.rejects(harness().call({action:'invent'}),{code:'invalid-argument'});});
for(const tier of Object.keys(PRICES))test('checkout uses fixed '+tier+' price and owner identity',async()=>{const h=harness();await h.call({action:'checkout',tier,price:'price_attacker',uid:'other'});const [,args,opts]=h.calls.find(c=>c[0]==='checkout');assert.equal(args.line_items[0].price,PRICES[tier]);assert.equal(args.client_reference_id,'owner');assert.equal(args.subscription_data.metadata.fynx_uid,'owner');assert.equal(args.metadata.product,PRODUCT);assert.equal(args.mode,'subscription');assert.match(opts.idempotencyKey,/fynx-consumer-live-checkout-/);assert.equal(h.data.get('fynxConsumerLive/owner').checkoutLockUntil,0);});
test('wrong price configuration prevents checkout',async()=>{const h=harness({price:{unit_amount:1}});await assert.rejects(h.call({action:'checkout',tier:'starter'}),{code:'failed-precondition'});assert.equal(h.calls.length,0);});
test('ambiguous Stripe failure reuses saved idempotency key',async()=>{const h=harness();h.state.failCreate=true;await assert.rejects(h.call({action:'checkout',tier:'starter'}));h.state.failCreate=false;await h.call({action:'checkout',tier:'starter'});const calls=h.calls.filter(c=>c[0]==='checkout');assert.equal(calls[0][2].idempotencyKey,calls[1][2].idempotencyKey);});
test('open same-tier checkout is reused',async()=>{const h=harness({customer:true});h.state.sessions=[{url:'https://checkout.stripe.com/existing',metadata:{product:PRODUCT,tier:'starter'}}];assert.equal((await h.call({action:'checkout',tier:'starter'})).url,'https://checkout.stripe.com/existing');assert.equal(h.calls.length,0);});
test('existing unpaid subscription blocks duplicate payment and still permits billing portal',async()=>{const h=harness({paid:true});h.state.subscriptions[0].status='past_due';await assert.rejects(h.call({action:'checkout',tier:'starter'}),{code:'already-exists'});assert.equal((await h.call({action:'status'})).hasBillingAccount,true);assert.match((await h.call({action:'portal'})).url,/billing.stripe.com/);});
test('revocation is checked on the next tool request',async()=>{const h=harness({paid:true});assert.equal((await h.call({action:'status'})).tier,'starter');h.state.subscriptions[0].status='canceled';await assert.rejects(h.call({action:'run',product:'watchlist',input:{symbols:['AAPL']}}),{code:'permission-denied'});});
test('payment API outage never grants tools',async()=>{await assert.rejects(harness({customer:true,stripeDown:true}).call({action:'run',product:'watchlist',input:{symbols:['AAPL']}}),/Stripe unavailable/);});
test('higher-tier tools are denied and saved work is owner-scoped',async()=>{const h=harness({paid:true});await assert.rejects(h.call({action:'run',product:'portfolio',input:{}}),{code:'permission-denied'});await h.call({action:'save',product:'watchlist',name:'Research',input:{symbols:['AAPL']}});assert.equal((await h.call({action:'list'})).items.length,1);await assert.rejects(h.call({action:'list'},'other'),{code:'permission-denied'});});
test('paid workspace quota is enforced transactionally',async()=>{const h=harness({paid:true});h.data.set('fynxConsumerLive/owner',{customer:'cus_owner',savedCount:25});await assert.rejects(h.call({action:'save',product:'watchlist',name:'Extra',input:{symbols:['AAPL']}}),{code:'resource-exhausted'});});
