'use strict';
const PRODUCTS=['analytics','risk','scenarios','review','export','watchlist','portfolio','simulation'];
const PLANS={starter:{name:'Essential',cents:599,products:PRODUCTS.slice(0,6),saved:25},plus:{name:'Plus',cents:1099,products:PRODUCTS.slice(0,7),saved:100},pro:{name:'Professional',cents:3099,products:PRODUCTS,saved:500}};
function number(v,name,min=0,max=1e9){if(v===''||v===null||v===undefined||!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)throw Error(`${name} must be between ${min} and ${max}.`);return Number(v);}
function label(v,max=120){if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('Enter a valid name.');return v.trim();}
function analytics(trades){const values=trades.map(t=>Number(t.pl)).filter(Number.isFinite);let equity=0,peak=0,drawdown=0;const curve=values.map(pl=>{equity+=pl;peak=Math.max(peak,equity);drawdown=Math.max(drawdown,peak-equity);return equity;});const wins=values.filter(x=>x>0),losses=values.filter(x=>x<0),grossWin=wins.reduce((a,b)=>a+b,0),grossLoss=-losses.reduce((a,b)=>a+b,0);return {trades:values.length,netPL:equity,winRate:values.length?wins.length/values.length*100:0,expectancy:values.length?equity/values.length:0,profitFactor:grossLoss?grossWin/grossLoss:null,maxDrawdown:drawdown,curve,notice:'Based on recorded realized P/L, in account currency. No starting balance or deposits are assumed.'};}
function risk(d){const balance=number(d.balance,'Balance',1),riskPct=number(d.riskPct,'Risk percent',0.01,100),entry=number(d.entry,'Entry',0.000001),stop=number(d.stop,'Stop',0.000001),target=number(d.target,'Target',0.000001),multiplier=number(d.multiplier??1,'Contract multiplier',0.000001),rate=number(d.rate??1,'Quote-to-account rate',0.000001);if(entry===stop||(entry-stop)*(target-entry)<=0)throw Error('Stop and target must lie on opposite sides of entry.');const budget=balance*riskPct/100,perUnit=Math.abs(entry-stop)*multiplier*rate,units=Math.floor(budget/perUnit*1e6)/1e6;return {riskBudget:budget,units,lossAtStop:units*perUnit,profitAtTarget:units*Math.abs(target-entry)*multiplier*rate,rewardRisk:Math.abs(target-entry)/Math.abs(entry-stop),notice:'Model only. Units use your contract multiplier and conversion rate. Fees, slippage and broker lot increments are excluded.'};}
function csv(trades){const safe=v=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"'$&").replace(/"/g,'""')+'"';return {csv:'Date,Symbol,Session,Realized P/L,Notes\r\n'+trades.map(t=>[t.date,t.symbol,t.session,t.pl,t.notes].map(safe).join(',')).join('\r\n'),rows:trades.length};}
function run(product,d={},trades=[]){
 if(product==='analytics')return analytics(trades);
 if(product==='export')return csv(trades);
 if(product==='risk')return risk(d);
 if(product==='scenarios'){const base=risk(d);return {base,scenarios:[0.5,1,1.5,2].map(f=>({riskMultiplier:f,...risk({...d,riskPct:Math.min(100,Number(d.riskPct)*f)})}))};}
 if(product==='review'){const notes=label(d.notes,2000),checks=['plan','risk','event','execution','review'];return {notes,completed:checks.filter(k=>d[k]===true),missing:checks.filter(k=>d[k]!==true),score:checks.filter(k=>d[k]===true).length*20,notice:'Self-assessment of your trading process, not a performance rating.'};}
 if(product==='watchlist'){if(!Array.isArray(d.symbols)||d.symbols.length<1||d.symbols.length>30)throw Error('Add 1–30 symbols.');return {symbols:[...new Set(d.symbols.map(s=>label(s,30).toUpperCase()))],notes:typeof d.notes==='string'?d.notes.slice(0,2000):'',notice:'A saved research list. Prices are not supplied by this tool.'};}
 if(product==='portfolio'){const balance=number(d.balance,'Balance',1),shock=number(d.shock,'Shock percent',-100,100);if(!Array.isArray(d.positions)||!d.positions.length||d.positions.length>30)throw Error('Enter 1–30 positions.');const rows=d.positions.map(p=>{const value=number(p.value,'Signed position value',-1e9,1e9);return {symbol:label(p.symbol,30),value,scenarioPL:value*shock/100};});const grossExposure=rows.reduce((a,p)=>a+Math.abs(p.value),0),netExposure=rows.reduce((a,p)=>a+p.value,0),scenarioPL=rows.reduce((a,p)=>a+p.scenarioPL,0);return {rows,grossExposure,netExposure,scenarioPL,scenarioEquity:balance+scenarioPL,grossLeverage:grossExposure/balance,notice:'Parallel price-shock model. Enter signed notionals in one account currency. Not VaR; ignores correlations, options nonlinearity, fees and liquidation.'};}
 if(product==='simulation'){const balance=number(d.balance,'Balance',1),riskPct=number(d.riskPct,'Risk percent',0.01,20),winRate=number(d.winRate,'Win rate',0,100)/100,rewardRisk=number(d.rewardRisk,'Reward/risk',0.01,20),count=Math.floor(number(d.trades,'Trades',1,500));let seed=123456789;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const end=[],drawdowns=[];let representative=[];for(let p=0;p<500;p++){let eq=balance,peak=balance,dd=0;const curve=[eq];for(let i=0;i<count;i++){eq*=1+(random()<winRate?rewardRisk:-1)*riskPct/100;if(!Number.isFinite(eq))throw Error('These assumptions exceed the simulation range. Reduce the trade count, risk or payoff.');peak=Math.max(peak,eq);dd=Math.max(dd,(peak-eq)/peak*100);curve.push(eq);}end.push(eq);drawdowns.push(dd);if(p===0)representative=curve;}end.sort((a,b)=>a-b);drawdowns.sort((a,b)=>a-b);return {paths:500,endingEquityP10:end[49],endingEquityMedian:end[249],endingEquityP90:end[449],drawdownP90:drawdowns[449],lossFrequency:end.filter(v=>v<balance).length/5,curve:representative,notice:'Hypothetical fixed-fractional simulation with independent trades and your assumed win rate/payoff. No fees or slippage; not a forecast. Fixed seed makes comparisons repeatable.'};}
 throw Error('Unknown product.');
}
function planForSubscription(sub,uid){if(!sub||sub.status!=='active'||sub.livemode!==false||sub.metadata?.product!=='fynx_consumer_test'||sub.metadata?.fynx_uid!==uid)return null;const tier=sub.metadata.tier,p=Object.hasOwn(PLANS,tier)?PLANS[tier]:null,item=sub.items?.data?.[0];return p&&sub.items.data.length===1&&item.quantity===1&&item.price?.currency==='usd'&&item.price.unit_amount===p.cents&&item.price.recurring?.interval==='month'&&item.price.recurring?.interval_count===1?tier:null;}
module.exports={PLANS,PRODUCTS,run,planForSubscription};
