const {test}=require('node:test');const assert=require('node:assert/strict');const e=require('./developer-engine.cjs');
const x={instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1',lot_step:'0.01',minimum_lot:'0.01',account_balance:'10000',risk_percent:'1',entry_price:'1.0850',stop_loss_price:'1.0820',direction:'long'};
const r=e.rules({name:'QA',starting_balance:'100000',daily_loss_percent:'5',max_loss_percent:'10',profit_target_percent:'8',max_loss_type:'static',consistency_percent:'40',min_trading_days:5,reset_hour_utc:22});
function event(a,delta,u='0',positions=0){return e.event(a,r,{sequence:a.sequence+1,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:delta,unrealized_pnl_after:u,open_position_count:positions});}
test('EURUSD flooring and exact budget boundary',()=>{assert.equal(e.risk('position-size',x).position_size,'0.33');assert.equal(e.risk('position-size',x).actual_risk_amount,'99.00');assert.equal(e.risk('position-size',{...x,risk_percent:undefined,risk_amount:'98.999999999'}).position_size,'0.32');});
test('direction, decimal and invalid rate validation',()=>{assert.throws(()=>e.risk('position-size',{...x,stop_loss_price:'1.09'}));assert.throws(()=>e.risk('position-size',{...x,risk_percent:1}));assert.throws(()=>e.risk('position-size',{...x,quote_to_account_rate:'0'}));});
test('risk reward and expectancy',()=>{const v=e.risk('risk-reward',{...x,take_profit_price:'1.0940',estimated_win_rate:'0.4'});assert.equal(v.rr_ratio,'3');assert.equal(v.expectancy_r,'0.6');});
test('margin and break even',()=>{assert.equal(e.risk('margin',{...x,lot_size:'1',leverage:'30'}).required_margin,'3616.67');assert.equal(e.risk('break-even',{...x,pip_size:'0.0001',entry_basis:'spread_excluded',spread_pips:'1.2',round_trip_commission_per_lot:'7'}).break_even_price,'1.08519');});
test('marks replace unrealized and closing does not double count',()=>{let a=e.account(r,'2026-09-20T12:00:00Z');a=event(a,'0','-150',1);a=event(a,'-150');assert.equal(a.equity,'99850');});
test('hard breach persists after recovery; equality follows rule',()=>{let a=e.account(r,'2026-09-20T12:00:00Z');a=event(a,'-5000');assert.equal(a.status,'active');a=event(a,'-1');assert.equal(a.status,'breached');a=event(a,'10000');assert.equal(a.status,'breached');});
test('first positive day consistency is recoverable',()=>{let a=event(e.account(r,'2026-09-20T12:00:00Z'),'1000');assert.equal(a.status,'active');assert.equal(a.metrics.consistency_share_percent,'100');assert.equal(a.metrics.consistency_met,false);});
test('ordered events and boundary gaps fail explicitly',()=>{let a=event(e.account(r,'2026-09-20T12:00:00Z'),'0','100',1);assert.throws(()=>e.event(a,r,{sequence:2,event_type:'equity_mark',timestamp:'2026-09-21T12:00:00Z',unrealized_pnl_after:'100',open_position_count:1}),/reset/);assert.throws(()=>e.event(a,r,{sequence:4}),/Sequence/);});
test('locked trailing floor remains initial and usage is 80%',()=>{const tr={...r,max_loss_type:'trailing_locked'};let a=e.account(tr,'2026-09-20T12:00:00Z');a=e.event(a,tr,{sequence:1,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:'12000',unrealized_pnl_after:'0',open_position_count:0});a=e.event(a,tr,{sequence:2,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:'-10000',unrealized_pnl_after:'0',open_position_count:0});assert.equal(a.metrics.max_floor,'100000');assert.equal(a.metrics.max_used_percent,'80');});
test('JPY conversion and ATR directions',()=>{assert.equal(e.risk('pip-value',{...x,symbol:'USDJPY',pip_size:'0.01',lot_size:'1',quote_to_account_rate:'0.00625'}).pip_value,'6.25');assert.equal(e.risk('atr-stop',{entry_price:'100',atr_value:'3',multiplier:'2',direction:'short'}).stop_loss_price,'106');assert.throws(()=>e.risk('atr-stop',{entry_price:'1',atr_value:'3',multiplier:'2',direction:'long'}));});
test('sizing budget invariant across lots and conversions',()=>{const D=require('decimal.js');for(const rate of ['0.00625','1','1.372849'])for(const budget of ['0.01','1.999999999','99','1000000'])for(const step of ['0.001','0.01','0.25']){const v=e.risk('position-size',{...x,risk_percent:undefined,risk_amount:budget,quote_to_account_rate:rate,lot_step:step,minimum_lot:step});assert(new D(v.actual_risk_unrounded).lte(budget));assert(new D(v.position_size).mod(step).eq(0));}});
test('overnight snapshots do not double count P&L',()=>{let a=event(e.account(r,'2026-09-19T21:00:00Z'),'0','-100',1);a=e.event(a,r,{sequence:2,event_type:'boundary_snapshot',timestamp:'2026-09-19T22:00:00Z',unrealized_pnl_after:'-200',open_position_count:1});assert.equal(a.balance,'100000');assert.equal(a.equity,'99800');assert.equal(a.daily_start,'100000');a=e.event(a,r,{sequence:3,event_type:'closed_trade',timestamp:'2026-09-19T22:01:00Z',realized_pnl:'-200',unrealized_pnl_after:'0',open_position_count:0});assert.equal(a.equity,'99800');});
test('boundary cannot erase daily loss or skip resets',()=>{let a=event(e.account(r,'2026-09-19T21:00:00Z'),'-4000','0',1);assert.throws(()=>e.event(a,r,{sequence:2,event_type:'boundary_snapshot',timestamp:'2026-09-20T22:00:00Z',unrealized_pnl_after:'0',open_position_count:1}));a=e.event(a,r,{sequence:2,event_type:'boundary_snapshot',timestamp:'2026-09-19T22:00:00Z',unrealized_pnl_after:'-1001',open_position_count:1});assert.equal(a.status,'breached');assert.deepEqual(a.breach.reasons,['daily_loss']);});
test('marks reject realized changes and breached accounts cannot be eligible',()=>{const a=e.account(r,'2026-09-20T12:00:00Z');assert.throws(()=>e.event(a,r,{sequence:1,event_type:'equity_mark',timestamp:a.last_timestamp,realized_pnl:'100',unrealized_pnl_after:'0',open_position_count:0}));const simple={...r,min_trading_days:1,consistency_percent:null};let b=e.event(a,simple,{sequence:1,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:'-5001',unrealized_pnl_after:'0',open_position_count:0});b=e.event(b,simple,{sequence:2,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:'20000',unrealized_pnl_after:'0',open_position_count:0});assert.equal(b.eligible,false);});
test('quota caps and retry fingerprints',()=>{const {payloadHash,entitlement,effectiveCap,validateInput}=require('./developer-core.cjs');assert.equal(payloadHash({z:1,a:{y:2,x:3}}),payloadHash({a:{x:3,y:2},z:1}));assert.notEqual(payloadHash({a:'1'}),payloadHash({a:1}));assert.equal(entitlement({plan:'pro',planCheckedUntil:200},'test',100).monthlyCalls,1000);assert.equal(entitlement({plan:'pro',planCheckedUntil:200},'live',300).monthlyCalls,1000);assert.equal(entitlement({plan:'pro',planCheckedUntil:200},'live',100).monthlyCalls,50000);assert.equal(effectiveCap({requestCap:20},{monthlyCalls:1000}),20);assert.equal(effectiveCap({requestCap:9999},{monthlyCalls:1000}),1000);assert(!validateInput([]));assert(!validateInput({large:'a'.repeat(20000)}));});
test('extreme decimal inputs match independent integer arithmetic',()=>{
 const f=s=>{const [a,b='']=s.split('.');return [BigInt(a+b),10n**BigInt(b.length)];};
 for(const budget of ['999999999999999999.999999999999','0.000000000001'])for(const rate of ['999999999999999999.999999999999','0.000000000001']){
  const q={...x,risk_percent:undefined,risk_amount:budget,entry_price:'1.000000000002',stop_loss_price:'1.000000000001',contract_size:'0.000000000001',quote_to_account_rate:rate,lot_step:'0.000000000001',minimum_lot:'0.000000000001'};
  const [bn,bd]=f(budget),[rn,rd]=f(rate),v=e.risk('position-size',q),[sn,sd]=f(v.position_size);
  const expected=bn*rd*10n**36n/(bd*rn);assert.equal(sn*10n**12n/sd,expected);
 }
});
