const {test}=require('node:test');const assert=require('node:assert/strict');const e=require('./developer-engine.cjs');
const x={instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1',lot_step:'0.01',minimum_lot:'0.01',account_balance:'10000',risk_percent:'1',entry_price:'1.0850',stop_loss_price:'1.0820',direction:'long'};
const r=e.rules({name:'QA',starting_balance:'100000',daily_loss_percent:'5',max_loss_percent:'10',profit_target_percent:'8',max_loss_type:'static',consistency_percent:'40',min_trading_days:5,reset_hour_utc:22});
function event(a,delta,u='0',positions=0){return e.event(a,r,{sequence:a.sequence+1,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:delta,unrealized_pnl_after:u,open_position_count:positions});}
test('EURUSD flooring and exact budget boundary',()=>{assert.equal(e.risk('position-size',x).position_size,'0.33');assert.equal(e.risk('position-size',x).actual_risk_amount,'99.00');assert.equal(e.risk('position-size',{...x,risk_percent:undefined,risk_amount:'98.999999999'}).position_size,'0.32');});
test('direction, decimal and invalid rate validation',()=>{assert.throws(()=>e.risk('position-size',{...x,stop_loss_price:'1.09'}));assert.throws(()=>e.risk('position-size',{...x,risk_percent:1}));assert.throws(()=>e.risk('position-size',{...x,quote_to_account_rate:'0'}));});
test('risk reward and expectancy',()=>{const v=e.risk('risk-reward',{...x,take_profit_price:'1.0940',estimated_win_rate:'0.4'});assert.equal(v.rr_ratio,'3');assert.equal(v.expectancy_r,'0.6');});
test('margin and break even',()=>{assert.equal(e.risk('margin',{...x,lot_size:'1',leverage:'30'}).required_margin,'3616.67');assert.equal(e.risk('break-even',{...x,pip_size:'0.0001',entry_basis:'spread_excluded',spread_pips:'1.2',round_trip_commission_per_lot:'7'}).break_even_price,'1.08519');});
test('marks replace unrealized and closing does not double count',()=>{let a=e.account(r,'2026-09-20T12:00:00Z');a=event(a,'0','-150',1);a=event(a,'-150');assert.equal(a.equity,'99850');});
test('hard breach persists after recovery; equality follows rule',()=>{let a=e.account(r,'2026-09-20T12:00:00Z');a=event(a,'-5000');assert.equal(a.status,'active');a=event(a,'-1');assert.equal(a.status,'breached');a=event(a,'10000');assert.equal(a.status,'breached');});
test('first positive day consistency is recoverable',()=>{let a=event(e.account(r,'2026-09-20T12:00:00Z'),'1000');assert.equal(a.status,'active');assert.equal(a.metrics.consistency_share_percent,'100');assert.equal(a.metrics.consistency_met,false);});
test('ordered events and boundary gaps fail explicitly',()=>{let a=event(e.account(r,'2026-09-20T12:00:00Z'),'0','100',1);assert.throws(()=>e.event(a,r,{sequence:2,event_type:'equity_mark',timestamp:'2026-09-21T12:00:00Z',unrealized_pnl_after:'100',open_position_count:1}),/reset/);assert.throws(()=>e.event(a,r,{sequence:4}),/Sequence/);});
test('locked trailing floor remains initial and usage is 80%',()=>{const tr={...r,max_loss_type:'trailing_locked'};let a=e.account(tr,'2026-09-20T12:00:00Z');a=e.event(a,tr,{sequence:1,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:'12000',unrealized_pnl_after:'0',open_position_count:0});a=e.event(a,tr,{sequence:2,event_type:'closed_trade',timestamp:a.last_timestamp,realized_pnl:'-10000',unrealized_pnl_after:'0',open_position_count:0});assert.equal(a.metrics.max_floor,'100000');assert.equal(a.metrics.max_used_percent,'80');});
