'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {PRICE,PRODUCT,validPrice,paidSubscription}=require('./developer-billing-policy.cjs');
const {entitlement,effectiveCap}=require('./developer-core.cjs');
function subscription(){return {id:'sub_owner',customer:'cus_owner',livemode:true,status:'active',metadata:{product:PRODUCT,fynx_uid:'owner'},items:{data:[{quantity:1,price:{id:PRICE,active:true,livemode:true,type:'recurring',currency:'usd',unit_amount:4900,recurring:{interval:'month',interval_count:1,usage_type:'licensed'}}}]},latest_invoice:{customer:'cus_owner',livemode:true,status:'paid',paid:true}};}
function harness(options={}){
 const records=new Map([['fynxDevelopers/owner',{name:'QA',plan:'free',requestCap:1000,...(options.customer?{stripeLiveCustomer:'cus_owner'}:{}),...options.profile}]]),calls=[];let serial=0;
 const snap=p=>({exists:records.has(p),data:()=>records.get(p)});
 const ref=p=>({path:p,get:async()=>snap(p),set:async(v,o)=>records.set(p,o?.merge?{...records.get(p),...v}:v),collection:n=>({doc:id=>ref(p+'/'+n+'/'+(id||'auto'+ ++serial))})});
 const db={collection:p=>({doc:id=>ref(p+'/'+id)}),runTransaction:async f=>f({get:async r=>snap(r.path),set:(r,v,o)=>r.set(v,o),create:(r,v)=>r.set(v)})};
 const state={subs:options.paid?[subscription()]:[],sessions:[],failure:false,down:false};
 const stripe={subscriptions:{list:async()=>{calls.push(['subscriptions']);if(state.down)throw Error('Stripe unavailable');if(options.onList)options.onList(records,state);return {data:state.subs};}},prices:{retrieve:async()=>({...subscription().items.data[0].price,...options.price})},customers:{create:async(...args)=>{calls.push(['customer',...args]);return {id:'cus_owner'};}},invoices:{list:async()=>({data:[]})},checkout:{sessions:{list:async()=>({data:state.sessions}),retrieve:async()=>({status:'expired'}),create:async(...args)=>{calls.push(['checkout',...args]);if(state.failure)throw Error('Timeout');return {id:'cs_owner',url:'https://checkout.stripe.com/qa'};}}},billingPortal:{configurations:{create:async()=>({id:'bpc'})},sessions:{create:async args=>{calls.push(['portal',args]);return {url:'https://billing.stripe.com/qa'};}}}};
 class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
 const stubs={'firebase-functions/v1':{https:{HttpsError},runWith:()=>({https:{onCall:f=>f}})},'firebase-functions/logger':{info(){},error(){}},'firebase-admin':{firestore:()=>db,auth:()=>({getUser:async()=>({email:'owner@example.invalid',emailVerified:true,...options.user})})},stripe:function(){return stripe;}};
 const module={exports:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/developer-billing.cjs','utf8'),{module,exports:module.exports,require:n=>stubs[n]||require(n),Date,process:{env:{FYNX_API_STRIPE_SECRET_KEY:options.key||'sk_live_UNIT_TEST_ONLY'}}});
 return {state,records,calls,refresh:force=>module.exports.refresh('owner',force),call:(action,uid='owner')=>module.exports._test.billing({action},uid?{auth:{uid}}:{})};
}
test('only the exact paid live API subscription qualifies',()=>{assert(paidSubscription(subscription(),'owner','cus_owner'));for(const mutate of [s=>s.livemode=false,s=>s.status='past_due',s=>s.customer='other',s=>s.metadata.fynx_uid='other',s=>s.metadata.product='fynx_consumer_live',s=>s.items.data[0].price.id='price_other',s=>s.items.data[0].price.unit_amount=1,s=>s.items.data[0].price.currency='eur',s=>s.items.data[0].price.recurring.interval='year',s=>s.items.data[0].quantity=2,s=>s.items.data.push(s.items.data[0]),s=>s.latest_invoice='in_unexpanded',s=>s.latest_invoice.paid=false,s=>s.latest_invoice.livemode=false,s=>s.latest_invoice.customer='other',s=>s.pause_collection={behavior:'void'}]){const s=subscription();mutate(s);assert.equal(paidSubscription(s,'owner','cus_owner'),false);}assert.equal(validPrice(null),false);});
test('auth, verified email, enabled user and live key required',async()=>{await assert.rejects(harness().call('checkout',null),{code:'unauthenticated'});await assert.rejects(harness({user:{emailVerified:false}}).call('checkout'),{code:'failed-precondition'});await assert.rejects(harness({user:{disabled:true}}).call('checkout'),{code:'failed-precondition'});await assert.rejects(harness({key:'sk_test_SAMPLE'}).call('checkout'),{code:'failed-precondition'});});
test('legacy test customers never confer live entitlement',async()=>{const h=harness({profile:{stripeCustomer:'cus_test',plan:'pro',planCheckedUntil:Date.now()+60000}});assert.equal((await h.refresh()).plan,'free');await h.call('checkout');assert.equal(h.calls.find(c=>c[0]==='checkout')[1].customer,'cus_owner');});
test('fixed live price, customer binding and recurrence used by checkout',async()=>{const h=harness();await h.call('checkout');const args=h.calls.find(c=>c[0]==='checkout')[1];assert.equal(args.line_items[0].price,PRICE);assert.equal(args.mode,'subscription');assert.equal(args.subscription_data.metadata.fynx_uid,'owner');assert.equal(args.client_reference_id,'owner');assert.match(args.success_url,/checkout=complete#billing/);});
test('invalid configured price prevents all customer and checkout creation',async()=>{const h=harness({price:{unit_amount:1}});await assert.rejects(h.call('checkout'),{code:'failed-precondition'});assert.equal(h.calls.length,0);});
test('repeat clicks reuse an open checkout',async()=>{const h=harness({customer:true});h.state.sessions=[{url:'https://checkout.stripe.com/existing',metadata:{product:PRODUCT,fynx_uid:'owner'}}];assert.match((await h.call('checkout')).url,/existing/);assert.equal(h.calls.filter(c=>c[0]==='checkout').length,0);});
test('ambiguous checkout timeout reuses the persisted idempotency key',async()=>{const h=harness();h.state.failure=true;await assert.rejects(h.call('checkout'));h.state.failure=false;await h.call('checkout');const c=h.calls.filter(c=>c[0]==='checkout');assert.equal(c[0][2].idempotencyKey,c[1][2].idempotencyKey);});
test('active and unsettled subscriptions block a second purchase',async()=>{for(const status of ['active','past_due','incomplete','unpaid','paused','trialing']){const h=harness({customer:true,paid:true});h.state.subs[0].status=status;await assert.rejects(h.call('checkout'),{code:'already-exists'});}});
test('paid upgrade grants 50,000 calls/30 per second and lifts only the default cap',async()=>{const h=harness({paid:true,customer:true});await h.refresh();const profile=h.records.get('fynxDevelopers/owner'),limits=entitlement(profile,'live');assert.equal(limits.monthlyCalls,50000);assert.equal(limits.rps,30);assert.equal(effectiveCap(profile,limits),50000);assert.equal(entitlement(profile,'test').monthlyCalls,1000);});
test('explicit and previously edited lower caps are preserved',async()=>{for(const profile of [{requestCap:500},{requestCap:1000,updatedAt:1},{requestCap:1000,requestCapExplicit:true}]){const h=harness({paid:true,customer:true,profile});await h.refresh();assert.equal(h.records.get('fynxDevelopers/owner').requestCap,profile.requestCap);}});
test('cache lasts at most 60 seconds and force refresh applies cancellation',async()=>{const h=harness({paid:true,customer:true});await h.refresh();h.state.subs[0].status='canceled';assert.equal((await h.refresh()).plan,'pro');assert.equal((await h.refresh(true)).plan,'free');assert.equal(entitlement(h.records.get('fynxDevelopers/owner'),'live').monthlyCalls,1000);});
test('expired cache and Stripe outage fail closed',async()=>{const h=harness({paid:true,customer:true});await h.refresh();h.state.down=true;await assert.rejects(h.refresh(true),/Stripe unavailable/);assert.equal(entitlement(h.records.get('fynxDevelopers/owner'),'live').plan,'free');});
test('billing portal remains available after failed payment',async()=>{const h=harness({customer:true,paid:true});h.state.subs[0].status='past_due';assert.match((await h.call('portal')).url,/billing.stripe.com/);});
test('a concurrent webhook invalidation cannot be overwritten by a stale refresh',async()=>{let first=true;const h=harness({paid:true,customer:true,onList:records=>{if(first){first=false;const p=records.get('fynxDevelopers/owner');records.set('fynxDevelopers/owner',{...p,billingRevision:1});}}});assert.equal((await h.refresh()).plan,'pro');assert.equal(h.calls.filter(c=>c[0]==='subscriptions').length,2);});
