'use strict';
const functions=require('firebase-functions/v1'),logger=require('firebase-functions/logger');
const {createHash}=require('node:crypto');
const OPS={auth:['auth-login','auth-signup','auth-reset','session-bootstrap'],upload:['photo-upload'],save:['profile-save','preferences-save','security-save','notifications-save','journal-save','cloud-save','waitlist-save'],feed:['feed-load','macro-load','feed-probe'],runtime:['runtime']};
const CODES=new Set(['unknown','network','timeout','permission-denied','unauthenticated','unavailable','resource-exhausted','invalid-argument','auth/invalid-credential','auth/wrong-password','auth/user-not-found','auth/too-many-requests','auth/network-request-failed','auth/popup-blocked','auth/popup-closed-by-user','auth/operation-not-allowed','auth/invalid-verification-code','storage/unauthorized','storage/retry-limit-exceeded','storage/quota-exceeded','storage/unknown','storage/canceled']);
function sanitize(d){if(!d||!OPS[d.category]?.includes(d.operation))return null;return{category:d.category,operation:d.operation,code:CODES.has(d.code)?d.code:'unknown',page:typeof d.page==='string'&&/^\/(?:[a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_.-]*$/.test(d.page)&&d.page.length<=100?d.page:'unknown'};}
function recordFailure(data,origin='server'){const safe=sanitize(data);if(safe)logger.write({severity:safe.category==='auth'?'WARNING':'ERROR',message:'FYNX operational failure',monitor:'fynx-web',origin,...safe});}
const buckets=new Map();
exports.webOperationalEvent=functions.runWith({timeoutSeconds:10,memory:'256MB',maxInstances:2}).https.onRequest((req,res)=>{
 const origin=req.get('origin');if(!['https://www.fynxfinanceworld.com','https://fynxfinanceworld.com'].includes(origin))return res.status(403).end();
 res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Cache-Control','no-store');
 if(req.method==='OPTIONS'){res.set('Access-Control-Allow-Methods','POST');res.set('Access-Control-Allow-Headers','Content-Type');return res.status(204).end();}
 if(req.method!=='POST')return res.status(405).end();const safe=sanitize(req.body);if(!safe)return res.status(400).json({error:'Invalid event'});
 const minute=Math.floor(Date.now()/60000),bucket=createHash('sha256').update(`${minute}:${req.ip}`).digest('hex');if(buckets.size>5000)buckets.clear();const count=buckets.get(bucket)||0;if(count>=20)return res.status(429).end();buckets.set(bucket,count+1);
 recordFailure(safe,'browser');return res.status(202).json({accepted:true});
});
exports.webFeedHealth=functions.runWith({timeoutSeconds:120,memory:'256MB',maxInstances:1}).pubsub.schedule('every 15 minutes').onRun(async()=>{
 await require('./holiday-notices').check().catch(()=>recordFailure({category:'feed',operation:'feed-probe',code:'unavailable',page:'/tools/market-holidays.html'},'holiday-monitor'));
 const checks=[['macro-rates','https://us-central1-fynx-c7a28.cloudfunctions.net/webMacroData?kind=rates',d=>Array.isArray(d.rows)&&d.rows.length===8&&d.rows.every(r=>Date.now()-Date.parse(r.observationDate)<21*86400000)&&d.cacheStatus!=='stale'&&Date.now()-Date.parse(d.fetchedAt)<86400000],['macro-indicators','https://us-central1-fynx-c7a28.cloudfunctions.net/webMacroData?kind=indicators',d=>Array.isArray(d.rows)&&d.rows.length>=8&&d.rows.every(r=>Number(r.year)>=new Date().getUTCFullYear()-3)&&d.cacheStatus!=='stale'&&Date.now()-Date.parse(d.fetchedAt)<86400000],['market-news','https://us-central1-fynx-c7a28.cloudfunctions.net/webMarketFeed?category=all',d=>Array.isArray(d.items)&&d.items.length>0&&!d.stale&&d.items.some(i=>Date.now()-Date.parse(i.pubDate)<72*3600000)],['cot','https://publicreporting.cftc.gov/resource/6dca-aqww.json?$select=report_date_as_yyyy_mm_dd&$order=report_date_as_yyyy_mm_dd%20DESC&$limit=1',d=>Array.isArray(d)&&Date.now()-Date.parse(d[0]?.report_date_as_yyyy_mm_dd)<14*86400000],['correlation','https://us-central1-fynx-c7a28.cloudfunctions.net/webMarketAnalytics?kind=correlation',d=>!d.stale&&d.matrix?.length===6&&Date.now()-Date.parse(d.observationDate)<7*86400000],['liquidity','https://us-central1-fynx-c7a28.cloudfunctions.net/webMarketAnalytics?kind=liquidity',d=>!d.stale&&Date.now()-Date.parse(d.observationTime)<60000]];
 for (const category of ['forex','crypto','stocks','macro','commodities','world']) checks.push(['news-'+category,'https://us-central1-fynx-c7a28.cloudfunctions.net/webMarketFeed?category='+category,d=>Array.isArray(d.items)&&d.items.length>0&&!d.stale&&d.items.some(i=>Date.now()-Date.parse(i.pubDate)<10*86400000)]);
 await Promise.all(checks.map(async([provider,url,valid])=>{try{const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok||!valid(await r.json()))throw new Error('provider');logger.info('FYNX feed health',{monitor:'fynx-web-health',provider,healthy:true});}catch{recordFailure({category:'feed',operation:'feed-probe',code:'unavailable',page:'/'},'probe');logger.warn('FYNX feed probe failed',{monitor:'fynx-web-health',provider,healthy:false});}}));
});
exports.recordFailure=recordFailure;exports._test={sanitize};
