'use strict';
if(!process.argv.includes('--run-production')){console.error('Explicit --run-production required.');process.exit(1);}
const admin=require('firebase-admin'),{randomBytes}=require('node:crypto'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixtures,browserResult}=require('../../scripts/proof/calculator-parity.cjs');
admin.initializeApp({projectId:'fynx-c7a28',credential:admin.credential.applicationDefault()});
const base='https://us-central1-fynx-c7a28.cloudfunctions.net/';
(async()=>{let uid;try{
 const password=randomBytes(24).toString('hex'),email='fynx-api-proof-'+Date.now()+'@example.com';const user=await admin.auth().createUser({email,password,emailVerified:true});uid=user.uid;
 const signin=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyDGSYIB_YIpbWyUMJ1d-v00-xADnvaWckk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,returnSecureToken:true})});const {idToken}=await signin.json();assert(idToken);
 const call=async action=>{const r=await fetch(base+'developerWorkspace',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+idToken},body:JSON.stringify({data:{action,environment:'test',label:'First-party proof fixture'}})});const d=await r.json();assert(!d.error,d.error?.message);return d.result;};
 await call('bootstrap');const key=(await call('createKey')).key,rows=[];
 for(const f of fixtures){const sample=await browserResult({...f,mode:'pilot'});let response;for(let n=0;n<4;n++){response=await fetch(base+'developerGateway/v1/risk/'+f.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify(sample.input)});if(response.status!==429)break;await new Promise(r=>setTimeout(r,1100));}const d=await response.json();assert.equal(response.status,200,f.name);const actual=Number(Number(d.result[sample.resultKey]).toFixed(sample.precision)),browser=Number(sample.local);assert.equal(actual,browser,f.name);rows.push({case:f.name,browser,liveApi:actual,match:true,adapterInputVerified:true});}
 await new Promise(r=>setTimeout(r,1100));
 const quickstart=require('node:child_process').spawnSync(process.execPath,[path.resolve(__dirname,'../../api/examples/quickstart.mjs')],{env:{...process.env,FYNX_API_KEY:key},encoding:'utf8'});assert.equal(quickstart.status,0,quickstart.stderr);assert.equal(JSON.parse(quickstart.stdout).integration,'passed');
 const prop=require('node:child_process').spawnSync(process.execPath,[path.resolve(__dirname,'../../api/examples/prop-firm-quickstart.mjs')],{env:{...process.env,FYNX_API_KEY:key},encoding:'utf8'});assert.equal(prop.status,0,prop.stderr);assert(prop.stdout.includes('\"integration\": \"passed\"'));
 const report={propQuickstartInternallyVerified:true,quickstartInternallyVerified:true,externalBetaVerified:false,verifiedAt:new Date().toISOString(),mode:'temporary_qa_test_key',realCustomerHistories:false,rows};fs.writeFileSync(path.resolve(__dirname,'../../docs/proof/live-pilot-parity.json'),JSON.stringify(report,null,2)+'\n');console.log('PASS: all '+rows.length+' actual calculator adapters match the deployed HTTP Risk API.');
 }finally{if(uid){const db=admin.firestore(),keys=await db.collection('fynxDeveloperKeys').where('uid','==',uid).get();for(const d of keys.docs)await d.ref.delete();await db.recursiveDelete(db.collection('fynxDevelopers').doc(uid));await admin.auth().deleteUser(uid);console.log('Proof user and records removed.');}}})().catch(e=>{console.error(e.message);process.exitCode=1;});
