'use strict';
const fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const root=path.resolve(__dirname,'../..'),engine=require('../../backend/developer-engine.cjs');
const meta={instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1'};
const numeric=s=>Number(String(s).replace(/[^0-9.+-]/g,''));
const fixtures=[];
for(const [label,entry,stop,target,direction] of [['long','1.085','1.082','1.094','long'],['short','1.085','1.088','1.076','short'],['integer','100','90','120','long']])fixtures.push({name:'risk-reward/'+label,file:'risk-reward',marker:'function calculate()',invoke:'calculate()',fields:{entry,sl:stop,tp:target},output:'rrOut',endpoint:'risk-reward',input:{entry_price:entry,stop_loss_price:stop,take_profit_price:target,direction},result:'rr_ratio',digits:2});
for(const [label,rate,pip,lots] of [['USD','1','0.0001','1'],['JPY','0.00625','0.01','1'],['cross','1.25','0.0001','0.3']])fixtures.push({name:'pip/'+label,file:'pip',marker:'function calculate()',invoke:'calculate()',fields:{price:rate,pipIncrement:pip,lots},output:'yourOut',endpoint:'pip-value',input:{...meta,quote_to_account_rate:rate,pip_size:pip,lot_size:lots},result:'pip_value',digits:2});
for(const [label,pairType,price,rate] of [['USD quoted','usdQuoted','1.085','1'],['USD base','usdBase','160','0.00625'],['cross','cross','0.85','1.25']])fixtures.push({name:'margin/'+label,file:'margin',marker:'function calculateMargin()',invoke:'calculateMargin()',fields:{pairType,accountBalance:'10000',lotSize:'1',contractSize:'100000',entryPrice:price,leverage:'30',conversionRate:rate,pipSize:'0.0001',usedMarginExisting:'0'},output:'requiredMarginValue',endpoint:'margin',input:{...meta,entry_price:price,quote_to_account_rate:rate,lot_size:'1',leverage:'30'},result:'required_margin',digits:2});
for(const side of ['buy','sell'])fixtures.push({name:'break-even/'+side,file:'breakeven',marker:'function calc()',invoke:'calc()',fields:{type:side,entry:'1.085',lot:'0.5',spread:'1.2',commission:'3.5'},output:'be',endpoint:'break-even',input:{...meta,entry_price:'1.085',direction:side==='buy'?'long':'short',pip_size:'0.0001',spread_pips:'1.2',round_trip_commission_per_lot:'7',entry_basis:'spread_excluded'},result:'break_even_price',digits:5,innerText:true});
for(const [side,entry,atr,multiple] of [['buy','1.085','0.0045','2'],['sell','1.085','0.0045','1.5']])fixtures.push({name:'atr-stop/'+side,file:'atr-stop',marker:'function updateCalc()',invoke:`currentSide='${side}';currentMultiple=${multiple};updateCalc()`,fields:{entry,atrValue:atr,period:'14'},output:'stopOut',endpoint:'atr-stop',input:{entry_price:entry,atr_value:atr,multiplier:multiple,direction:side==='buy'?'long':'short'},result:'stop_loss_price',digits:5});
for(const [label,risk,stop] of [['exact','99','30'],['floor','100','15'],['below-minimum','1','30']])fixtures.push({name:'position-size/'+label,file:'position-size',marker:'async function pipValuePerLotUSD',invoke:"usePercentRisk=false;manualMode=true;currentPrice=1.085;els.manualPriceRow.style.display='grid';await calculate()",fields:{pair:'EUR/USD',balance:'10000',riskDollars:risk,stopPips:stop,manualPrice:'1.085',quoteUsdRate:'1'},output:'lotsOut',endpoint:'position-size',input:{...meta,entry_price:'1.085',stop_loss_price:String(1.085-Number(stop)*0.0001),direction:'long',risk_amount:risk,lot_step:'0.01',minimum_lot:'0.01'},result:'position_size',digits:2});
// Avoid binary subtraction in test inputs; explicit prices are independent of browser parsing.
fixtures.find(x=>x.name==='position-size/exact').input.stop_loss_price='1.082';fixtures.find(x=>x.name==='position-size/floor').input.stop_loss_price='1.0835';fixtures.find(x=>x.name==='position-size/below-minimum').input.stop_loss_price='1.082';
async function browserResult(f){
 const html=fs.readFileSync(path.join(root,'tools',f.file+'.html'),'utf8');const dom=new JSDOM(html,{runScripts:'outside-only',url:'https://www.fynxfinanceworld.com/tools/'+f.file+'.html'}),w=dom.window;
 w.alert=()=>{w.__alert=true;};w.fetch=async()=>{throw new Error('Network disabled in fixture test');};w.setInterval=()=>0;w.clearInterval=()=>{};
 const decimalFile=path.join(root,'assets/vendor/decimal.js');if(fs.existsSync(decimalFile))w.eval(fs.readFileSync(decimalFile,'utf8'));
 const script=[...w.document.querySelectorAll('script:not([src])')].map(x=>x.textContent).find(s=>s.includes(f.marker));if(!script)throw new Error('Calculator script missing: '+f.file);
 w.eval(script+'\nwindow.__proof=async()=>{'+f.invoke+';};');
 for(const [id,value]of Object.entries(f.fields)){const el=w.document.getElementById(id);if(!el)throw new Error('Missing field '+id);el.value=value;}
 await w.__proof();const node=w.document.getElementById(f.output),value=f.mode==='pilot'?await w.fynxRiskPilot():f.mode==='visible_error'?node.style.display==='block':f.mode==='alert'?!!w.__alert:f.mode==='error_text'?!!node.textContent.trim():numeric(f.innerText?node.innerText:node.textContent);w.close();return value;
}
async function run(){const rows=[];for(const f of fixtures){const browser=await browserResult(f),api=engine.risk(f.endpoint,f.input),expected=Number(Number(api[f.result]).toFixed(f.digits));rows.push({case:f.name,browser,api:expected,match:browser===expected});}return rows;}
module.exports={run,fixtures,browserResult};
if(require.main===module)run().then(rows=>{console.log(JSON.stringify(rows,null,2));if(rows.some(x=>!x.match))process.exitCode=1;}).catch(e=>{console.error(e);process.exitCode=1;});
