const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('assets/js/mfa.js','utf8').replace(/^import .*;$/gm,'').replace('export async function withMfa','window.withMfa=async function');
function setup(){const dom=new JSDOM('<section id="mfaSettings"><p role="status"></p><button disabled>Set up</button></section>',{runScripts:'outside-only'}),w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
w.auth={currentUser:{providerData:[],emailVerified:true}};w.multiFactor=()=>({enrolledFactors:[]});w.onAuthStateChanged=(_,callback)=>callback();w.TotpMultiFactorGenerator={FACTOR_ID:'totp',assertionForSignIn:(uid,code)=>({uid,code})};w.eval(source);return {dom,w};}
(async()=>{
 const {dom,w}=setup();assert.equal(w.document.querySelector('#mfaSettings button').disabled,true);assert.match(w.document.querySelector('[role=status]').textContent,/pending/);
 assert.equal(await w.withMfa(async()=>42),42);await assert.rejects(w.withMfa(async()=>{throw {code:'auth/invalid-credential'}}),e=>e.code==='auth/invalid-credential');
 let attempts=0;w.getMultiFactorResolver=()=>({hints:[{factorId:'totp',uid:'factor'}],resolveSignIn:async assertion=>{attempts++;if(assertion.code!=='123456')throw {code:'auth/invalid-verification-code',message:'Private Firebase raw error'};return 'signed-in'}});
 const promise=w.withMfa(async()=>{throw {code:'auth/multi-factor-auth-required'}});await new Promise(r=>setTimeout(r,0));const form=w.document.querySelector('dialog form'),input=form.querySelector('input');input.value='000000';form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,0));assert.match(form.querySelector('[role=status]').textContent,/invalid or expired/);assert(!form.textContent.includes('Firebase'));assert.equal(form.querySelector('button').disabled,false);input.value='123456';form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(await promise,'signed-in');assert.equal(attempts,2);assert.equal(w.document.querySelector('dialog'),null);
 const cancelled=w.withMfa(async()=>{throw {code:'auth/multi-factor-auth-required'}});const rejection=assert.rejects(cancelled,e=>e.code==='auth/cancelled');await new Promise(r=>setTimeout(r,0));w.document.querySelector('dialog button[type=button]').click();await rejection;assert.equal(w.document.querySelector('dialog'),null);dom.window.close();console.log('PASS MFA challenge, invalid-code retry, cancellation cleanup, safe messages and inactive enrollment gate');
})().catch(e=>{console.error(e);process.exitCode=1});
