import {withMfa} from '/assets/js/mfa.js';
import {app,auth,authPersistenceReady} from '/auth/firebase.js';
import {onAuthStateChanged,GoogleAuthProvider,OAuthProvider,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut,reload} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import {getFunctions,httpsCallable} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-functions.js';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const funcs=getFunctions(app,'us-central1');let state=null,env='test',busy=false;
const endpoint='https://us-central1-fynx-c7a28.cloudfunctions.net/developerGateway';
const call=async(action,data={})=>{const r=(await httpsCallable(funcs,'developerWorkspace',{timeout:60000})({action,environment:env,...data})).data;if(action==='run'&&r.status>=400&&data.route?.startsWith('/v1/propfirm/'))throw new Error(r.error?.message||'Event rejected.');return r;};
const bill=async(action)=>(await httpsCallable(funcs,'developerBilling',{timeout:60000})({action})).data;
function notice(text,bad=false){$('#notice').textContent=text;$('#notice').className=bad?'error':'';}
async function task(fn){if(busy)return;busy=true;document.querySelectorAll('#panel button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message||'Request failed. Please retry.',true);}finally{busy=false;document.querySelectorAll('#panel button').forEach(b=>b.disabled=false);}}
const date=v=>v?new Date(v).toLocaleString():'—';
const json=v=>'<pre>'+escape(JSON.stringify(v,null,2))+'</pre>';
const table=(cols,rows)=>'<div class="table-wrap" tabindex="0"><table><thead><tr>'+cols.map(c=>'<th>'+escape(c)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const empty=s=>'<p class="empty">'+escape(s)+'</p>';
const field=(name,label,value='',type='text')=>`<label>${escape(label)}<input name="${name}" type="${type}" value="${escape(value)}" required></label>`;
const select=(name,label,opts)=>`<label>${label}<select name="${name}">${opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
const formData=f=>Object.fromEntries(new FormData(f));
const presets={
 'position-size':{instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1',lot_step:'0.01',minimum_lot:'0.01',account_balance:'10000',risk_percent:'1',entry_price:'1.0850',stop_loss_price:'1.0820',direction:'long'},
 'risk-reward':{entry_price:'1.0850',stop_loss_price:'1.0820',take_profit_price:'1.0940',direction:'long',estimated_win_rate:'0.40'},
 'pip-value':{instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1',pip_size:'0.0001',lot_size:'1'},
 'margin':{instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1',lot_size:'1',entry_price:'1.0850',leverage:'30'},
 'break-even':{instrument_type:'forex',symbol:'EURUSD',account_currency:'USD',contract_size:'100000',quote_to_account_rate:'1',pip_size:'0.0001',entry_price:'1.0850',direction:'long',entry_basis:'spread_excluded',spread_pips:'1.2',round_trip_commission_per_lot:'7'},
 'atr-stop':{entry_price:'1.0850',atr_value:'0.0045',multiplier:'2',direction:'long'}
};
async function load(){if(!auth.currentUser)return;state=await call('bootstrap');$('#auth-panel').hidden=true;$('#app').hidden=false;$('#signout').hidden=false;$('#verification').hidden=state.emailVerified;notice('');render();}
function render(){
 if(!state)return;const page=location.hash.slice(1)||'overview';document.querySelectorAll('.ws-nav a').forEach(a=>{if(a.hash==='#'+page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const panel=$('#panel');
 const titles={overview:'Workspace overview',keys:'API keys',playground:'Request playground',history:'Request history',rules:'Rule sets',accounts:'Accounts & events',billing:'Billing & invoices',settings:'Settings & support'};
 panel.innerHTML=`<p class="eyebrow">${escape(env.toUpperCase())} ENVIRONMENT <span class="pill">${escape(state.limits.plan)}</span></p><h1>${titles[page]||titles.overview}</h1>`;
 if(page==='overview'){
 panel.innerHTML+=`<p>${escape(state.profile.name)} · Usage resets on the first of each month at 00:00 UTC.</p><div class="stats"><div class="stat"><span>SUCCESSFUL CALLS / ${escape(state.month)}</span><strong>${state.usage.calls.toLocaleString()}</strong></div><div class="stat"><span>INCLUDED MONTHLY CALLS</span><strong>${state.limits.monthlyCalls.toLocaleString()}</strong></div><div class="stat"><span>REQUESTS / SECOND</span><strong>${state.limits.rps}</strong></div></div><p>Saved monthly request cap: ${state.profile.requestCap?.toLocaleString()||'Plan allowance'}. ${env==='test'?'Test usage is unbilled.':'No automatic overage charges.'}</p><h2>Recent requests</h2>`+historyMarkup(state.requests)+`<h2>Connect from your server</h2><p>Use the gateway URL below followed by an endpoint path. Send your key in the Authorization header.</p>`+json({base_url:endpoint,example_path:'/v1/risk/position-size',authorization:'Bearer YOUR_KEY'})+'<p class="help">Contract values are supplied by you. Examples are not broker-verified instrument specifications.</p>';
 }else if(page==='keys'){
 panel.innerHTML+='<p>Keys are scoped to this environment. Secrets are displayed only once. Rotation immediately revokes the old key.</p><form id="key-form">'+field('label','Key label','My integration')+'<button class="button primary">Create API key</button></form>'+(state.keys.length?table(['Label','Key prefix','Created','Status','Actions'],state.keys.map(k=>[escape(k.label),'<code>'+escape(k.prefix)+'</code>',escape(date(k.createdAt)),k.revokedAt?'Revoked':'Active',k.revokedAt?'—':`<button data-rotate="${escape(k.id)}">Rotate</button> <button data-revoke="${escape(k.id)}">Revoke</button>`])):empty('No keys in this environment. Create one after verifying your email.'));
 $('#key-form').onsubmit=e=>{e.preventDefault();task(async()=>{const result=await call('createKey',formData(e.target));await load();showKey(result.key);});};
 panel.querySelectorAll('[data-rotate],[data-revoke]').forEach(b=>b.onclick=()=>{const rotate=!!b.dataset.rotate;if(!confirm(rotate?'Rotate this key? The old key will stop working immediately.':'Revoke this key? Requests using it will stop working immediately.'))return;task(async()=>{const r=await call(rotate?'rotateKey':'revokeKey',{id:b.dataset.rotate||b.dataset.revoke,label:'Rotated key'});await load();if(r.key)showKey(r.key);});});
 }else if(page==='playground'){
 panel.innerHTML+='<p>Runs a real server-side calculation and records the request in this environment. Successful calls count toward its allowance.</p><form id="run-form">'+select('endpoint','Calculation',Object.keys(presets).map(x=>[x,x]))+'<label>JSON input<textarea id="request-input" spellcheck="false"></textarea></label><button class="button primary">Run request</button></form><p class="help">Examples use caller-supplied metadata. The engine does not fetch prices or guarantee execution outcomes.</p><div id="response" aria-live="polite"></div>';
 const picker=$('#run-form select');const fill=()=>{$('#request-input').value=JSON.stringify(presets[picker.value],null,2);};fill();picker.onchange=fill;
 $('#run-form').onsubmit=e=>{e.preventDefault();task(async()=>{const result=await call('run',{route:'/v1/risk/'+picker.value,input:JSON.parse($('#request-input').value)});$('#response').innerHTML='<h2>Response · '+result.status+'</h2>'+json(result);});};
 }else if(page==='history'){
 panel.innerHTML+='<p>Successful operations and validation failures. Authentication and gateway rejection errors are returned directly to the caller.</p><div id="history-list">'+historyMarkup(state.requests)+'</div><button id="older">Load older requests</button>';
 let before=state.requests.at(-1)?.at,beforeId=state.requests.at(-1)?.id;$('#older').onclick=()=>task(async()=>{if(!before){notice('No more requests.');return;}const r=await call('history',{before,beforeId});$('#history-list').insertAdjacentHTML('beforeend',historyMarkup(r.items));before=r.items.at(-1)?.at;beforeId=r.items.at(-1)?.id;if(!before)$('#older').hidden=true;});
 }else if(page==='rules'){
 panel.innerHTML+='<p>Rule sets are immutable. Create a new version for changed policies. This release uses USD, boundary-balance daily loss and an explicit UTC reset hour.</p><form id="rule-form"><div class="form-grid">'+field('name','Rule set name','Evaluation phase 1')+field('starting_balance','Starting balance','100000')+field('daily_loss_percent','Daily loss %','5')+field('max_loss_percent','Maximum loss %','10')+field('profit_target_percent','Profit target %','8')+field('consistency_percent','Consistency %','40')+field('min_trading_days','Minimum trading days','5','number')+field('reset_hour_utc','Daily reset hour UTC (0–23)','22','number')+select('max_loss_type','Maximum loss model',[['static','Static'],['trailing','Trailing equity'],['trailing_locked','Trailing, capped at initial balance']])+'</div><label><input name="breach_on_touch" type="checkbox"> Breach when equity touches the floor</label><button class="button primary">Create rule set</button></form><h2>Saved rule sets</h2>'+ (state.rules.length?state.rules.map(r=>'<details><summary>'+escape(r.name)+' · '+escape(r.id)+'</summary>'+json(r)+'</details>').join(''):empty('No rule sets yet.'));
 $('#rule-form').onsubmit=e=>{e.preventDefault();task(async()=>{const input=formData(e.target);input.breach_on_touch=input.breach_on_touch==='on';await call('run',{route:'/v1/propfirm/rule-sets',input});await load();notice('Rule set saved.');});};
 }else if(page==='accounts'){
 panel.innerHTML+='<p>Each account is a separate phase ledger. Status reflects submitted events; it is not a payout approval or proof of complete broker history.</p>'+(state.rules.length?'<form id="account-form">'+field('name','Account name','Evaluation account')+select('rule_set_id','Rule set',state.rules.map(r=>[escape(r.id),escape(r.name)]))+'<button class="button primary">Create account</button></form>':empty('Create a rule set first.'))+'<h2>Your accounts</h2>'+(state.accounts.length?table(['Account','Balance / equity','Status','Events'],state.accounts.map(a=>[escape(a.name),escape(a.balance)+' / '+escape(a.equity),escape(a.status),`<button data-account="${escape(a.id)}">Open account</button>`])):empty('No accounts in this environment.'))+'<div id="account-detail"></div>';
 if($('#account-form'))$('#account-form').onsubmit=e=>{e.preventDefault();task(async()=>{await call('run',{route:'/v1/propfirm/accounts',input:formData(e.target)});await load();notice('Account created.');});};
 panel.querySelectorAll('[data-account]').forEach(b=>b.onclick=()=>task(async()=>{const a=state.accounts.find(x=>x.id===b.dataset.account);const h=await call('history',{accountId:a.id});$('#account-detail').innerHTML='<h2>'+escape(a.name)+'</h2>'+json({account_id:a.id,status:a.status,metrics:a.metrics||{},breach:a.breach,last_timestamp:a.last_timestamp,sequence:a.sequence})+'<form id="event-form"><label>Ordered account event<textarea id="event-input"></textarea></label><button class="button primary">Submit event</button></form><h3>Event history</h3>'+h.items.map(ev=>'<details><summary>'+escape(date(ev.at))+' · '+escape(ev.id)+'</summary>'+json(ev)+'</details>').join('');const older=document.createElement('button');older.textContent='Load older events';$('#account-detail').append(older);let lastEvent=h.items.at(-1);older.onclick=()=>task(async()=>{if(!lastEvent){notice('No more events.');return;}const more=await call('history',{accountId:a.id,before:lastEvent.at,beforeId:lastEvent.id});older.insertAdjacentHTML('beforebegin',more.items.map(ev=>'<details><summary>'+escape(date(ev.at))+' · '+escape(ev.id)+'</summary>'+json(ev)+'</details>').join(''));lastEvent=more.items.at(-1);if(!lastEvent)older.hidden=true;});$('#event-input').value=JSON.stringify({idempotency_key:crypto.randomUUID(),source_event_id:crypto.randomUUID(),sequence:a.sequence+1,event_type:'closed_trade',timestamp:new Date().toISOString(),realized_pnl:'0.00',unrealized_pnl_after:'0.00',open_position_count:0},null,2);$('#event-form').onsubmit=e=>{e.preventDefault();task(async()=>{const r=await call('run',{route:'/v1/propfirm/accounts/'+a.id+'/events',input:JSON.parse($('#event-input').value)});await load();notice('Event saved. Account status: '+r.result.status);});};}));
 }else if(page==='billing'){
 panel.innerHTML+='<p>Billing applies to your workspace’s live environment. Test calls are unbilled.</p><div class="stats"><div class="stat"><span>FREE</span><strong>$0</strong><span>1,000 calls/month · 10/sec</span></div><div class="stat"><span>PRO</span><strong>$49/mo</strong><span>50,000 live calls/month · 30/sec</span></div><div class="stat"><span>AUTOMATIC OVERAGES</span><strong>$0</strong><span>Requests stop at the allowance or your lower cap</span></div></div><p>Monthly subscription renews until cancelled. Usage allowances reset at UTC calendar-month boundaries; subscription invoices follow your purchase date. Limits are shared across all keys in an environment.</p><div class="actions"><button id="billing-refresh">Refresh billing & invoices</button><button id="upgrade">Subscribe to Pro — $49/month</button><button id="portal">Manage billing / cancel</button></div><div id="billing-data"></div>';
 if(state.billing_mode==='test'){panel.insertAdjacentHTML('afterbegin','<p class="notice">Paid plans are on the waitlist while Stripe is in test mode. No payment details or charges are collected.</p>');$('#upgrade').textContent=state.profile.proWaitlist?'You’re on the Pro waitlist':'Join Pro waitlist — no payment';$('#portal').hidden=true;}
 $('#billing-refresh').onclick=()=>task(async()=>{const r=await bill('summary');$('#billing-data').innerHTML='<h2>Subscription</h2>'+json({plan:r.plan,subscription:r.subscription})+'<h2>Invoices</h2>'+(r.invoices.length?table(['Invoice','Status','Amount','Download'],r.invoices.map(i=>[escape(i.number||i.id),escape(i.status),escape((i.amount_due/100).toFixed(2)+' '+i.currency),i.url?`<a href="${escape(i.url)}" target="_blank" rel="noopener">View invoice ↗</a>`:'Pending'])):empty('No invoices. You have not been charged through this workspace.'));});
 $('#upgrade').onclick=()=>task(async()=>{if(state.billing_mode==='live'&&!confirm('Continue to Stripe Checkout for a $49/month subscription? No charge is made until you complete Checkout.'))return;const r=await bill('checkout');if(r.waitlist){await load();notice(r.message);}else location.assign(r.url);});
 $('#portal').onclick=()=>task(async()=>{const r=await bill('portal');location.assign(r.url);});
 }else if(page==='settings'){
 panel.innerHTML+='<form id="settings-form">'+field('name','Workspace name',state.profile.name)+field('requestCap','Monthly request cap (per environment)',state.profile.requestCap||1000,'number')+'<p class="help">This cap can lower your included allowance. Raising it never buys extra calls. Plan allowances still apply; there is no automatic overage billing.</p><button class="button primary">Save settings</button></form><h2>Account</h2><p>'+escape(auth.currentUser.email)+'</p><p>Use the password-reset option on sign-in to change your password.</p><h2>Support</h2><p>Submit an internal support ticket or email <a href="mailto:support@fynxfunded.com">support@fynxfunded.com</a>. Do not include API keys or personal trader records.</p><form id="support-form">'+field('subject','Subject')+'<label>Message<textarea name="message" minlength="10" maxlength="4000" required></textarea></label><button class="button">Save support ticket</button></form>';
 $('#settings-form').onsubmit=e=>{e.preventDefault();task(async()=>{await call('settings',formData(e.target));await load();notice('Settings saved.');});};$('#support-form').onsubmit=e=>{e.preventDefault();task(async()=>{const r=await call('support',formData(e.target));e.target.reset();notice('Support ticket saved: '+r.ticket_id);});};
 }else {location.hash='overview';}
}
function historyMarkup(items){return items.length?items.map(r=>'<details><summary>'+escape(date(r.at))+' · '+escape(r.status)+' · '+escape(r.route)+'</summary>'+json(r)+'</details>').join(''):empty('No recorded requests yet. Try the playground.');}
function showKey(key){$('#new-key').value=key;$('#key-dialog').showModal();}
$('#close-key').onclick=()=>$('#key-dialog').close();$('#key-dialog').addEventListener('close',()=>{$('#new-key').value='';});
$('#auth-form').onsubmit=e=>{e.preventDefault();task(async()=>{await withMfa(()=>signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value));});};
$('#signup').onclick=()=>task(async()=>{if(!$('#auth-form').reportValidity())return;await createUserWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);});
$('#google-signin').onclick=()=>task(async()=>{await withMfa(()=>signInWithPopup(auth,new GoogleAuthProvider()));});
$('#apple-signin').onclick=()=>task(async()=>{await withMfa(()=>signInWithPopup(auth,new OAuthProvider('apple.com')));});
$('#reset-password').onclick=()=>task(async()=>{if(!$('#email').reportValidity())return;await sendPasswordResetEmail(auth,$('#email').value.trim());notice('Password-reset instructions requested. Check your inbox.');});
$('#verify-email').onclick=()=>task(async()=>{await sendEmailVerification(auth.currentUser,{url:'https://www.fynxfinanceworld.com/api/workspace.html'});notice('Verification email sent.');});
$('#refresh-verification').onclick=()=>task(async()=>{await reload(auth.currentUser);await auth.currentUser.getIdToken(true);await load();});
$('#signout').onclick=()=>task(async()=>{await signOut(auth);state=null;$('#password').value='';$('#new-key').value='';$('#key-dialog').close();});
$('#environment').onchange=()=>task(async()=>{env=$('#environment').value;await load();});
window.addEventListener('hashchange',()=>{if(auth.currentUser)load().catch(e=>notice(e.message,true));});
await authPersistenceReady;
onAuthStateChanged(auth,user=>{if(user)load().catch(e=>notice(e.message,true));else{$('#auth-panel').hidden=false;$('#app').hidden=true;$('#signout').hidden=true;$('#verification').hidden=true;notice('');}});
